# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quay < Formula
  desc "quay is a CLI tool designed to manage and filter Docker Compose services."
  homepage "https://github.com/yarlson/quay"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/quay/releases/download/0.2.0/quay_0.2.0_darwin_amd64.tar.gz"
      sha256 "3108c4e665b6fcefe2865f759e6be32f6f57a78889110bb0d95647de2be46dc0"

      def install
        bin.install "quay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/quay/releases/download/0.2.0/quay_0.2.0_darwin_arm64.tar.gz"
      sha256 "f8f927d8c95438c9a9f3e4f13787efeeb0dbcdd745f859633515a2d101fe1c5f"

      def install
        bin.install "quay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/quay/releases/download/0.2.0/quay_0.2.0_linux_amd64.tar.gz"
        sha256 "bc7210d367d19750137d07aba59124e8f58e985d06d46ebc3c6b8a5de93e08ef"

        def install
          bin.install "quay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/quay/releases/download/0.2.0/quay_0.2.0_linux_arm64.tar.gz"
        sha256 "3efef8c0431139feff0a79a5ff699235eeadb8a65e6d13e037f8fa0525e3a60a"

        def install
          bin.install "quay"
        end
      end
    end
  end

  test do
    system "#{bin}/quay --version"
  end
end
