# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quay < Formula
  desc "quay is a CLI tool designed to manage and filter Docker Compose services."
  homepage "https://github.com/yarlson/quay"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/quay/releases/download/0.1.0/quay_0.1.0_darwin_amd64.tar.gz"
      sha256 "0d3bcefd47dae8dfc1c657682ab2e3a9e45bbd761f6888d1ff909f8ab7192b05"

      def install
        bin.install "quay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/quay/releases/download/0.1.0/quay_0.1.0_darwin_arm64.tar.gz"
      sha256 "619c0789c2fa70211aec02496347b3cbd4db512f23186168b3fa70fbca38b36c"

      def install
        bin.install "quay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/quay/releases/download/0.1.0/quay_0.1.0_linux_amd64.tar.gz"
        sha256 "545b3f2360f611ca8ee8287b528e69b692cd91f24c49036cf1e7dc88f3e53b28"

        def install
          bin.install "quay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yarlson/quay/releases/download/0.1.0/quay_0.1.0_linux_arm64.tar.gz"
        sha256 "5723f8c53528648ee00374d93e9c3aa1e3230f65d32f4d0d74645a86f90c6cbc"

        def install
          bin.install "quay"
        end
      end
    end
  end

  test do
    system "#{bin}/quay --version"
  end
end
